function createfigure_airPassiveHeatGain(X1, YMatrix1, Y1)
%CREATEFIGURE(X1, YMATRIX1, Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  Y1:  stairs y

%  Auto-generated by MATLAB on 21-Nov-2017 19:13:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','Low Thermal Mass');
set(plot1(2),'DisplayName','High Thermal Mass');

% Create stairs
stairs(X1,Y1,'DisplayName','Occupancy','Color',[0.929 0.694 0.125]);

% Create xlabel
xlabel('Time (hr)');

% Create ylabel
ylabel('Heat Gain (W)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[0 12 24 36 48 60 72 84 96 108 120 132 144 156 168 180]);
% Create legend
legend(axes1,'show');

