function createfigure_TProfile(X1, Y1, X2, yvector1)
%CREATEFIGURE(X1, Y1, X2, YVECTOR1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  area x
%  YVECTOR1:  area yvector

%  Auto-generated by MATLAB on 21-Nov-2017 19:42:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1,'Color',[1 0 0]);

% Create area
area(X2,yvector1,'FaceAlpha',0.1,...
    'FaceColor',[0 0.447058826684952 0.74117648601532],...
    'LineStyle',':');

% Create xlabel
xlabel('Time (hr)');

% Create ylabel
ylabel('Temperature (°C)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 167]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[16 22]);
% Set the remaining axes properties
set(axes1,'XTick',[0 12 24 36 48 60 72 84 96 108 120 132 144 156 167]);
